# Generated by Django 5.2.14 on 2026-05-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_alter_demoprofile_demo_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demoprofile',
            name='demo_secret',
        ),
        migrations.AddField(
            model_name='demoprofile',
            name='_demo_secret_encrypted',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
