# Generated by Django 5.2.12 on 2026-06-01 19:40

import tom_common.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_alter_demoprofile_demo_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demoprofile',
            name='demo_secret',
            field=tom_common.encryption.EncryptedModelField(blank=True, editable=True, null=True),
        ),
    ]
